// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzvnkJgPjz9BacK2RHhuk0VjCptQ6A-Jo',
    appId: '1:1034688762816:web:f9ec924a68d318eef02e25',
    messagingSenderId: '1034688762816',
    projectId: 'noteapp-41adc',
    authDomain: 'noteapp-41adc.firebaseapp.com',
    storageBucket: 'noteapp-41adc.appspot.com',
    measurementId: 'G-GR233NRYJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk2HwE3ZF5qkNOf5l13bO6Hjbp5ETDg1o',
    appId: '1:1034688762816:android:26ff70c719cb8f71f02e25',
    messagingSenderId: '1034688762816',
    projectId: 'noteapp-41adc',
    storageBucket: 'noteapp-41adc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxK9EQcMBLjGpiW4t7BtfIRL42lR4GypQ',
    appId: '1:1034688762816:ios:23fa1ccfa9f1ef52f02e25',
    messagingSenderId: '1034688762816',
    projectId: 'noteapp-41adc',
    storageBucket: 'noteapp-41adc.appspot.com',
    iosClientId: '1034688762816-l08b40gcrf2842pch34vd5oro9v4lqpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxK9EQcMBLjGpiW4t7BtfIRL42lR4GypQ',
    appId: '1:1034688762816:ios:6695c84896c64df1f02e25',
    messagingSenderId: '1034688762816',
    projectId: 'noteapp-41adc',
    storageBucket: 'noteapp-41adc.appspot.com',
    iosClientId: '1034688762816-dm60s0cne6ka92jdcqmicvvkd21hnbi3.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFirebaseProject.RunnerTests',
  );
}
